"""Init

Revision ID: 37973729868
Revises: 
Create Date: 2014-12-25 01:23:29.871074

"""

# revision identifiers, used by Alembic.
revision = '37973729868'
down_revision = None
branch_labels = ()
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
