"""Add images and m2m

Revision ID: 4fbdb25ff6b
Revises: 161170fe476
Create Date: 2014-12-25 01:25:26.845373

"""

# revision identifiers, used by Alembic.
revision = '4fbdb25ff6b'
down_revision = '161170fe476'
branch_labels = ()
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
