"""Init with pure Alembic

Revision ID: 2b20375fa7c
Revises: 
Create Date: 2014-12-25 20:40:42.517760

"""

# revision identifiers, used by Alembic.
revision = '2b20375fa7c'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
