"""Add another models

Revision ID: 2bcb8ae6f3e
Revises: 6d935a38f3
Create Date: 2014-12-26 06:19:39.410387

"""

# revision identifiers, used by Alembic.
revision = '2bcb8ae6f3e'
down_revision = '6d935a38f3'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
