"""Init

Revision ID: 322a9b48c31
Revises: 
Create Date: 2014-12-26 06:18:01.121048

"""

# revision identifiers, used by Alembic.
revision = '322a9b48c31'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
