"""Add some models

Revision ID: 4d574ff692
Revises: 2b20375fa7c
Create Date: 2014-12-25 20:42:17.768303

"""

# revision identifiers, used by Alembic.
revision = '4d574ff692'
down_revision = '2b20375fa7c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
