"""Init

Revision ID: 51b35ea457a
Revises: 
Create Date: 2014-12-26 06:34:07.223099

"""

# revision identifiers, used by Alembic.
revision = '51b35ea457a'
down_revision = None
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
