"""Add json field

Revision ID: 6d935a38f3
Revises: 322a9b48c31
Create Date: 2014-12-26 06:19:02.991625

"""

# revision identifiers, used by Alembic.
revision = '6d935a38f3'
down_revision = '322a9b48c31'
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
